version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "apptemplate"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - docker-network
    restart: always

  app-template-api:
    container_name: app-template-api
    image: alanfirmiano/app-template-api:0.0.2-SNAPSHOT
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

networks:
  docker-network:
    driver: bridge